version: "3"

services:
    app:
        build: .
        ports:
            - 8090:80
    db:
        image: mariadb:10.5
        environment:
            - MARIADB_RANDOM_ROOT_PASSWORD=true
            - MARIADB_USER=lime
            - MARIADB_PASSWORD=lime
            - MARIADB_DATABASE=lime